In [42]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import seaborn as sns
import matplotlib.pylab as plt
import plotly.express as px

import copy

import warnings
warnings.filterwarnings("ignore")

In [43]:
df = pd.read_csv('Flights1_2019_1.csv')
df = df.drop(['Unnamed: 17'], axis=1)
df.columns

Index(['YEAR', 'DAY_OF_WEEK', 'FL_DATE', 'ORIGIN_AIRPORT_ID',
       'ORIGIN_AIRPORT_SEQ_ID', 'ORIGIN_CITY_MARKET_ID', 'ORIGIN_CITY_NAME',
       'DEST_AIRPORT_ID', 'DEST_AIRPORT_SEQ_ID', 'DEST_CITY_MARKET_ID',
       'DEST_CITY_NAME', 'DEST_STATE_ABR', 'DEP_DELAY', 'ARR_TIME',
       'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15'],
      dtype='object')

In [44]:
df['ORIGIN_STATE_ABR'] = df['ORIGIN_CITY_NAME'].str[-2:]

df['DAY_OF_WEEK_STR'] = np.where(df['DAY_OF_WEEK'] == 1, 'Mon', df['DAY_OF_WEEK'])
df['DAY_OF_WEEK_STR'] = np.where(df['DAY_OF_WEEK'] == 2, 'Tue', df['DAY_OF_WEEK_STR'])
df['DAY_OF_WEEK_STR'] = np.where(df['DAY_OF_WEEK'] == 3, 'Wed', df['DAY_OF_WEEK_STR'])
df['DAY_OF_WEEK_STR'] = np.where(df['DAY_OF_WEEK'] == 4, 'Thu', df['DAY_OF_WEEK_STR'])
df['DAY_OF_WEEK_STR'] = np.where(df['DAY_OF_WEEK'] == 5, 'Fri', df['DAY_OF_WEEK_STR'])
df['DAY_OF_WEEK_STR'] = np.where(df['DAY_OF_WEEK'] == 6, 'Sat', df['DAY_OF_WEEK_STR'])
df['DAY_OF_WEEK_STR'] = np.where(df['DAY_OF_WEEK'] == 7, 'Sun', df['DAY_OF_WEEK_STR'])

df['DEP_DELAY_NEW'] = np.where(df['DEP_DELAY'] <= 0, 0, df['DEP_DELAY'])
df['DEP_DEL15'] = np.where(df['DEP_DELAY'] >= 15, 1, 0)
df['DEP_DEL15'] = np.where(df['DEP_DELAY'] .isna(), np.NAN, df['DEP_DELAY'])

In [45]:
df

,YEAR,DAY_OF_WEEK,FL_DATE,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN_CITY_NAME,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,...,DEST_STATE_ABR,DEP_DELAY,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ORIGIN_STATE_ABR,DAY_OF_WEEK_STR,DEP_DELAY_NEW,DEP_DEL15
0,2019,6,2019-01-19,13487,1348702,31650,"Minneapolis, MN",11193,1119302,33105,...,KY,-10.0,1832.0,-25.0,0.0,0.0,MN,Sat,0.0,-10.0
1,2019,7,2019-01-20,13487,1348702,31650,"Minneapolis, MN",11193,1119302,33105,...,KY,-4.0,1825.0,-37.0,0.0,0.0,MN,Sun,0.0,-4.0
2,2019,1,2019-01-21,13487,1348702,31650,"Minneapolis, MN",11193,1119302,33105,...,KY,-9.0,1845.0,-17.0,0.0,0.0,MN,Mon,0.0,-9.0
3,2019,2,2019-01-22,13487,1348702,31650,"Minneapolis, MN",11193,1119302,33105,...,KY,-4.0,1839.0,-23.0,0.0,0.0,MN,Tue,0.0,-4.0
4,2019,3,2019-01-23,13487,1348702,31650,"Minneapolis, MN",11193,1119302,33105,...,KY,-6.0,1850.0,-12.0,0.0,0.0,MN,Wed,0.0,-6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583980,2019,3,2019-01-30,14057,1405702,34057,"Portland, OR",13930,1393007,30977,...,IL,-9.0,1225.0,-27.0,0.0,0.0,OR,Wed,0.0,-9.0
583981,2019,3,2019-01-30,13930,1393007,30977,"Chicago, IL",14908,1490803,32575,...,CA,35.0,2230.0,17.0,17.0,1.0,IL,Wed,35.0,35.0
583982,2019,3,2019-01-30,14635,1463502,31714,"Fort Myers, FL",13930,1393007,30977,...,IL,132.0,2035.0,113.0,113.0,1.0,FL,Wed,132.0,132.0
583983,2019,3,2019-01-30,11618,1161802,31703,"Newark, NJ",13930,1393007,30977,...,IL,32.0,841.0,37.0,37.0,1.0,NJ,Wed,32.0,32.0
583984,2019,3,2019-01-30,14107,1410702,30466,"Phoenix, AZ",13930,1393007,30977,...,IL,NaN,NaN,NaN,NaN,NaN,AZ,Wed,NaN,NaN

In [50]:
df.columns

Index(['YEAR', 'DAY_OF_WEEK', 'FL_DATE', 'ORIGIN_AIRPORT_ID',
       'ORIGIN_AIRPORT_SEQ_ID', 'ORIGIN_CITY_MARKET_ID', 'ORIGIN_CITY_NAME',
       'DEST_AIRPORT_ID', 'DEST_AIRPORT_SEQ_ID', 'DEST_CITY_MARKET_ID',
       'DEST_CITY_NAME', 'DEST_STATE_ABR', 'DEP_DELAY', 'ARR_TIME',
       'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15', 'ORIGIN_STATE_ABR',
       'DAY_OF_WEEK_STR', 'DEP_DELAY_NEW', 'DEP_DEL15'],
      dtype='object')

In [46]:
df.isna().sum()

YEAR                         0
DAY_OF_WEEK                  0
FL_DATE                      0
ORIGIN_AIRPORT_ID            0
ORIGIN_AIRPORT_SEQ_ID        0
ORIGIN_CITY_MARKET_ID        0
ORIGIN_CITY_NAME             0
DEST_AIRPORT_ID              0
DEST_AIRPORT_SEQ_ID          0
DEST_CITY_MARKET_ID          0
DEST_CITY_NAME               0
DEST_STATE_ABR               0
DEP_DELAY                16355
ARR_TIME                 17061
ARR_DELAY                18022
ARR_DELAY_NEW            18022
ARR_DEL15                18022
ORIGIN_STATE_ABR             0
DAY_OF_WEEK_STR              0
DEP_DELAY_NEW            16355
DEP_DEL15                16355
dtype: int64

In [47]:
df_withoutNAN = copy.deepcopy(df)

df_withoutNAN = df_withoutNAN.dropna(subset=['DEP_DELAY'])
df_withoutNAN = df_withoutNAN.dropna(subset=['ARR_TIME'])
df_withoutNAN = df_withoutNAN.dropna(subset=['ARR_DELAY'])

df_withoutNAN.shape

(565963, 21)

In [48]:
df_withoutNAN.isna().sum()

YEAR                     0
DAY_OF_WEEK              0
FL_DATE                  0
ORIGIN_AIRPORT_ID        0
ORIGIN_AIRPORT_SEQ_ID    0
ORIGIN_CITY_MARKET_ID    0
ORIGIN_CITY_NAME         0
DEST_AIRPORT_ID          0
DEST_AIRPORT_SEQ_ID      0
DEST_CITY_MARKET_ID      0
DEST_CITY_NAME           0
DEST_STATE_ABR           0
DEP_DELAY                0
ARR_TIME                 0
ARR_DELAY                0
ARR_DELAY_NEW            0
ARR_DEL15                0
ORIGIN_STATE_ABR         0
DAY_OF_WEEK_STR          0
DEP_DELAY_NEW            0
DEP_DEL15                0
dtype: int64

In [49]:
from google.colab import files
df.to_csv('Flights_2019_v2.csv', encoding = 'utf-8-sig')
files.download('Flights_2019_v2.csv')